backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "wedding"
    label: "Wedding Plans"
    folder: "content/wedding"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date",  label: "Date",  widget: "datetime" }
      - { name: "body",  label: "Body",  widget: "markdown" }

  - name: "wedding_timeline"
    label: "Wedding Timeline"
    folder: "content/wedding/timeline"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date",  label: "Date",  widget: "datetime" }
      - { name: "body",  label: "Body",  widget: "markdown" }


  - name: "garden"
    label: "Gardening Journal"
    folder: "content/garden"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date",  label: "Date",  widget: "datetime" }
      - { name: "body",  label: "Body",  widget: "markdown" }

  - name: "crafts"
    label: "Crafts & Gifts"
    folder: "content/crafts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date",  label: "Date",  widget: "datetime" }
      - { name: "body",  label: "Body",  widget: "markdown" }
